import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Header from "@/components/header";
import MapInfo from "@/components/map-info";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        <Providers>
          <div className="flex flex-col bg[#1B4242] h-screen">
            <Header />
            <div className="grid grid-cols-5 h-screen">
              <div className="col-span-2 bg-[#5C8374]">{children}</div>
              <div className="col-span-3">
                <MapInfo />
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
